export const complimentsList = [
  "You have the most beautiful eyes I've ever seen.",
  "Your smile lights up my entire day",
  "You look absolutely stunning",
  "You have the kindest heart I’ve ever known",
  "Your laugh is my favorite sound in the world",
  "You make me feel special",
  "I love how thoughtful you are",
  "I’m so proud of everything you’ve accomplished",
  "I admire your determination and hard work",
  "I love the way you light up when you talk about dogs",
  "You are cute (this is the ultimate compliment from me)",
  "Even when you’re not trying, you look effortlessly beautiful.",
  "Your confidence is one of the most attractive things about you",
  "You’re the perfect mix of kindness and strength.",
  "You’re not just beautiful outside, but your heart makes you extraordinary",
  "The way you handle challenges inspires me every day.",
  "You’re the cutest thing, and no one could ever convince me otherwise.",
];

export const dateideasList = [
  "Stargazing Night",
  "Sunrise or Sunset Watch",
  "Movie Night",
  "Board Game or Puzzle Night",
  "Photoshoot with dogs",
  "DIY Craft Night",
  "Zoo or Aquarium Visit",
  "Breakfast in Bed",
  "Bowling",
  "Old-School Ice Cream Date",
  "Write a Bucket List",
  "Escape Room",
  "Museum Date",
  "Photography Walk",
  "Gingerbread House Contest",
  "Retro Video Games",
  "Lego Building Date",
  "DIY Pizza Night",
];

export const favorsList = [
  "I’ll take you wherever you want to go, and you can enjoy being passenger princess ",
  "I'll cook your favorite meal",
  "I'll give you massage",
  "I’ll make you a warm cup of coffee or tea exactly how you like it.",
  "I’ll run your errands so you can focus on studying or resting",
  "I’ll set up a cozy movie night for us with all your favorite snacks",
  "I’ll walk your dogs so you can relax.",
  "I’ll listen to anything that’s on your mind or stressing you out.",
];
